repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: web-biom-check
        name: check linting and formating of web files
        language: system
        entry: bash -c "cd web && bun biome check"
        pass_filenames: false

      - id: server-biom-check
        name: check linting and formating of server files
        language: system
        entry: bash -c "cd server && bun biome check"
        pass_filenames: false

      - id: server-tests
        name: run server tests
        language: system
        entry: bash -c "cd server && bun test"
        pass_filenames: false
